### ISSUE TITLE
qrcode

### ISSUE THREAD

**Issue by stepollo2** [grupokindynos/polispay-releases#4]
quoted text from polispay support
"The QR code scanner is not working for me. It won't let me hold the reader over the code until it captures. The image disappears from the reader screen before it can be captured. To send Polis to new wallet holders, I had to copy their address and send to me by message or email."

**Comment by PrettyBoyHelios** [comment]
I think this vas fixed in v8.6.0, will close, feel free to reopen the thread if it is not
